### ISSUE TITLE
Errata p.88 .insert() words instead of nums

### ISSUE THREAD

**Issue by rubenbb85** [Connor-SM/python_bootcamp#1]
In the page 88, section **.insert()** there is an errata. Instead of using the list *words*, the example is using the list *nums*.

```diff
words = ['ball', 'base']
- nums.insert(0, 'glove') 
+ words.insert(0, "glove") 
```

File [Week_04.ipynb](https://github.com/Connor-SM/python_bootcamp/blob/master/Week_04.ipynb) should be updated too.

**Comment by Connor-SM** [comment]
The Jupyter Notebook file has been updated and this issue is resolved. Thanks for pointing this out!! 👍
