### ISSUE TITLE
Wrong indentation "hangman" project.

### ISSUE THREAD

**Issue by rubenbb85** [Connor-SM/python_bootcamp#3]
In the book, between pages 97 and 102, a lot of conditionals are indented at the same level as the If.

Example:

```diff
# create main game loop
    while not game_over:
    ans = input("Type quit or guess a letter: ").lower( )
    if ans == "quit":
-   print("Thanks for playing.")
+       print("Thanks for playing.")
-   game_over = True
+       game_over = True
```

**Comment by Connor-SM** [comment]
That's odd, when I reviewed the book it looked fine, must have been during the print run after I reviewed. I'll keep this in mind, although the source code should run fine, so it's always worth checking the source code if you're ever concerned! Thanks!
