### ISSUE TITLE
p.160 wrong line reference

### ISSUE THREAD

**Issue by rubenbb85** [Connor-SM/python_bootcamp#5]
I think, after adding some extra empty lines for readability, the line references have been offseted.

```diff
- Go ahead and run the cell. On the 6th line we print... 
+ Go ahead and run the cell. On the 9th line we print... 

- ...The entire 7th line is commented out because it...
+ ...The entire 11th line is commented out because it...

- ...Lastly, on the 9th line, after we instantiate...
+ ...Lastly, on the 15th line, after we instantiate...
```

**Comment by rubenbb85** [comment]
The page 158 has the same issue

**Comment by Connor-SM** [comment]
Oof, ya that should be corrected. I should have had you do the review it would be much better! haha I'll keep this noted for the revised edition in the future.
